# Dependencies
markdown:         
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Ethan Miles
tagline:         
description:      'Welcome! I am a Ph.D student in the Government Department at Harvard University.'
url:              http://ethanmiles.github.io
baseurl:          /

author:
  name:           'Ethan Miles'
  url:            https://twitter.com/ethantmiles

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ethanmiles/ethanmiles.github.io
